# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'View/config.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmConfig(object):
    def setupUi(self, frmConfig):
        frmConfig.setObjectName("frmConfig")
        frmConfig.resize(480, 320)
        self.btCanalPNP = QtWidgets.QPushButton(frmConfig)
        self.btCanalPNP.setGeometry(QtCore.QRect(10, 20, 140, 80))
        self.btCanalPNP.setObjectName("btCanalPNP")
        self.btCanalNPN = QtWidgets.QPushButton(frmConfig)
        self.btCanalNPN.setGeometry(QtCore.QRect(170, 20, 140, 80))
        self.btCanalNPN.setObjectName("btCanalNPN")
        self.btCanalRele = QtWidgets.QPushButton(frmConfig)
        self.btCanalRele.setGeometry(QtCore.QRect(330, 20, 140, 80))
        self.btCanalRele.setObjectName("btCanalRele")
        self.txNomeProg = QtWidgets.QLineEdit(frmConfig)
        self.txNomeProg.setGeometry(QtCore.QRect(10, 141, 461, 31))
        self.txNomeProg.setObjectName("txNomeProg")
        self.label = QtWidgets.QLabel(frmConfig)
        self.label.setGeometry(QtCore.QRect(10, 120, 111, 16))
        self.label.setObjectName("label")
        self.btVoltar = QtWidgets.QPushButton(frmConfig)
        self.btVoltar.setGeometry(QtCore.QRect(390, 260, 80, 40))
        self.btVoltar.setObjectName("btVoltar")
        self.btAbrir = QtWidgets.QPushButton(frmConfig)
        self.btAbrir.setGeometry(QtCore.QRect(10, 260, 80, 40))
        self.btAbrir.setObjectName("btAbrir")

        self.retranslateUi(frmConfig)
        QtCore.QMetaObject.connectSlotsByName(frmConfig)

    def retranslateUi(self, frmConfig):
        _translate = QtCore.QCoreApplication.translate
        frmConfig.setWindowTitle(_translate("frmConfig", "Form"))
        self.btCanalPNP.setText(_translate("frmConfig", "Canal PNP"))
        self.btCanalNPN.setText(_translate("frmConfig", "Canal NPN"))
        self.btCanalRele.setText(_translate("frmConfig", "Canal Relé"))
        self.txNomeProg.setText(_translate("frmConfig", "Texto"))
        self.label.setText(_translate("frmConfig", "Nome Programa"))
        self.btVoltar.setText(_translate("frmConfig", "Voltar"))
        self.btAbrir.setText(_translate("frmConfig", "Abrir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    frmConfig = QtWidgets.QWidget()
    ui = Ui_frmConfig()
    ui.setupUi(frmConfig)
    frmConfig.show()
    sys.exit(app.exec_())
