# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'View/menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(480, 320)
        self.btConfigProg = QtWidgets.QPushButton(Form)
        self.btConfigProg.setGeometry(QtCore.QRect(20, 50, 140, 80))
        self.btConfigProg.setStyleSheet("")
        self.btConfigProg.setObjectName("btConfigProg")
        self.btInitProg = QtWidgets.QPushButton(Form)
        self.btInitProg.setGeometry(QtCore.QRect(320, 50, 140, 80))
        self.btInitProg.setObjectName("btInitProg")
        self.btTestOutNPN = QtWidgets.QPushButton(Form)
        self.btTestOutNPN.setGeometry(QtCore.QRect(20, 190, 140, 80))
        self.btTestOutNPN.setStyleSheet("")
        self.btTestOutNPN.setObjectName("btTestOutNPN")
        self.btTestOutPNP = QtWidgets.QPushButton(Form)
        self.btTestOutPNP.setGeometry(QtCore.QRect(170, 190, 140, 80))
        self.btTestOutPNP.setStyleSheet("")
        self.btTestOutPNP.setObjectName("btTestOutPNP")
        self.btTestOutRelay = QtWidgets.QPushButton(Form)
        self.btTestOutRelay.setGeometry(QtCore.QRect(320, 190, 140, 80))
        self.btTestOutRelay.setStyleSheet("")
        self.btTestOutRelay.setObjectName("btTestOutRelay")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btConfigProg.setToolTip(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.btConfigProg.setText(_translate("Form", "Configurar\n"
"Programas"))
        self.btInitProg.setText(_translate("Form", "Iniciar\n"
"Programas"))
        self.btTestOutNPN.setToolTip(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.btTestOutNPN.setText(_translate("Form", "Testar\n"
"Saida NPN"))
        self.btTestOutPNP.setToolTip(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.btTestOutPNP.setText(_translate("Form", "Testar\n"
"Saida PNP"))
        self.btTestOutRelay.setToolTip(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.btTestOutRelay.setText(_translate("Form", "Testar\n"
"Saida Rele"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
