# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'View/teste_saidas.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmTesteSaidas(object):
    def setupUi(self, frmTesteSaidas):
        frmTesteSaidas.setObjectName("frmTesteSaidas")
        frmTesteSaidas.resize(480, 320)
        self.label = QtWidgets.QLabel(frmTesteSaidas)
        self.label.setGeometry(QtCore.QRect(23, 20, 81, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(frmTesteSaidas)
        self.label_2.setGeometry(QtCore.QRect(143, 20, 81, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(frmTesteSaidas)
        self.label_3.setGeometry(QtCore.QRect(263, 20, 81, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(frmTesteSaidas)
        self.label_4.setGeometry(QtCore.QRect(383, 20, 81, 31))
        self.label_4.setObjectName("label_4")
        self.btLigaCanal1 = QtWidgets.QPushButton(frmTesteSaidas)
        self.btLigaCanal1.setGeometry(QtCore.QRect(0, 70, 120, 60))
        self.btLigaCanal1.setStyleSheet("")
        self.btLigaCanal1.setObjectName("btLigaCanal1")
        self.btDesligaCanal1 = QtWidgets.QPushButton(frmTesteSaidas)
        self.btDesligaCanal1.setGeometry(QtCore.QRect(0, 140, 120, 60))
        self.btDesligaCanal1.setObjectName("btDesligaCanal1")
        self.btDesligaCanal2 = QtWidgets.QPushButton(frmTesteSaidas)
        self.btDesligaCanal2.setGeometry(QtCore.QRect(120, 140, 120, 60))
        self.btDesligaCanal2.setObjectName("btDesligaCanal2")
        self.btLigaCanal2 = QtWidgets.QPushButton(frmTesteSaidas)
        self.btLigaCanal2.setGeometry(QtCore.QRect(120, 70, 120, 60))
        self.btLigaCanal2.setObjectName("btLigaCanal2")
        self.btDesligaCanal3 = QtWidgets.QPushButton(frmTesteSaidas)
        self.btDesligaCanal3.setGeometry(QtCore.QRect(240, 140, 120, 60))
        self.btDesligaCanal3.setObjectName("btDesligaCanal3")
        self.btLigaCanal3 = QtWidgets.QPushButton(frmTesteSaidas)
        self.btLigaCanal3.setGeometry(QtCore.QRect(240, 70, 120, 60))
        self.btLigaCanal3.setObjectName("btLigaCanal3")
        self.btDesligaCanal4 = QtWidgets.QPushButton(frmTesteSaidas)
        self.btDesligaCanal4.setGeometry(QtCore.QRect(360, 140, 120, 60))
        self.btDesligaCanal4.setObjectName("btDesligaCanal4")
        self.btLigaCanal4 = QtWidgets.QPushButton(frmTesteSaidas)
        self.btLigaCanal4.setGeometry(QtCore.QRect(360, 70, 120, 60))
        self.btLigaCanal4.setObjectName("btLigaCanal4")
        self.btVoltar = QtWidgets.QPushButton(frmTesteSaidas)
        self.btVoltar.setGeometry(QtCore.QRect(390, 270, 80, 40))
        self.btVoltar.setObjectName("btVoltar")

        self.retranslateUi(frmTesteSaidas)
        QtCore.QMetaObject.connectSlotsByName(frmTesteSaidas)

    def retranslateUi(self, frmTesteSaidas):
        _translate = QtCore.QCoreApplication.translate
        frmTesteSaidas.setWindowTitle(_translate("frmTesteSaidas", "Form"))
        self.label.setText(_translate("frmTesteSaidas", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">CANAL 1</span></p></body></html>"))
        self.label_2.setText(_translate("frmTesteSaidas", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">CANAL 2</span></p></body></html>"))
        self.label_3.setText(_translate("frmTesteSaidas", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">CANAL 3</span></p></body></html>"))
        self.label_4.setText(_translate("frmTesteSaidas", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">CANAL 4</span></p></body></html>"))
        self.btLigaCanal1.setText(_translate("frmTesteSaidas", "LIGA"))
        self.btDesligaCanal1.setText(_translate("frmTesteSaidas", "DESLIGA"))
        self.btDesligaCanal2.setText(_translate("frmTesteSaidas", "DESLIGA"))
        self.btLigaCanal2.setText(_translate("frmTesteSaidas", "LIGA"))
        self.btDesligaCanal3.setText(_translate("frmTesteSaidas", "DESLIGA"))
        self.btLigaCanal3.setText(_translate("frmTesteSaidas", "LIGA"))
        self.btDesligaCanal4.setText(_translate("frmTesteSaidas", "DESLIGA"))
        self.btLigaCanal4.setText(_translate("frmTesteSaidas", "LIGA"))
        self.btVoltar.setText(_translate("frmTesteSaidas", "Voltar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    frmTesteSaidas = QtWidgets.QWidget()
    ui = Ui_frmTesteSaidas()
    ui.setupUi(frmTesteSaidas)
    frmTesteSaidas.show()
    sys.exit(app.exec_())
